# To determine the classification of Game results using Decision trees & Random Forests

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('../../data/processedLOLOracleData.csv')

In [3]:
df.head()

server summoner_name winner     BTop     BJng    BMid    BAdc    BSup  \
0     na          AnDa    Red  Camille   Gragas    Yone    Jhin   Brand   
1     na          AnDa   Blue  Camille  Nidalee   Galio    Jhin  Anivia   
2     na          AnDa   Blue   Irelia     Ekko   Annie  Kai'Sa  Thresh   
3     na          AnDa    Red   Graves  Kindred   Sylas   Vayne    Bard   
4     na          AnDa    Red  Camille  Lee Sin  Lucian  Kai'Sa   Leona   

       RTop       RJng     RMid          RAdc      RSup  \
0      Shen     Graves    Sylas        Kai'Sa     Karma   
1     Riven    Hecarim   Xerath  Miss Fortune   Vel'Koz   
2    Aatrox  Jarvan IV  Orianna      Aphelios    Maokai   
3  Renekton    Nidalee     Ekko         Sivir      Pyke   
4      Jhin    Nidalee     Yone       Orianna  Pantheon   

                          Time  
0  2020-12-23 14:12:18 26m 18s  
1  2020-12-23 13:19:48 20m 42s  
2  2020-12-22 15:11:07 15m 20s  
3  2020-12-22 14:46:00 30m 34s  
4  2020-12-22 13:59:22 29m 58s

In [4]:
df.drop(['server','summoner_name','Time'],axis=1,inplace=True)

In [5]:
df.head()

winner     BTop     BJng    BMid    BAdc    BSup      RTop       RJng  \
0    Red  Camille   Gragas    Yone    Jhin   Brand      Shen     Graves   
1   Blue  Camille  Nidalee   Galio    Jhin  Anivia     Riven    Hecarim   
2   Blue   Irelia     Ekko   Annie  Kai'Sa  Thresh    Aatrox  Jarvan IV   
3    Red   Graves  Kindred   Sylas   Vayne    Bard  Renekton    Nidalee   
4    Red  Camille  Lee Sin  Lucian  Kai'Sa   Leona      Jhin    Nidalee   

      RMid          RAdc      RSup  
0    Sylas        Kai'Sa     Karma  
1   Xerath  Miss Fortune   Vel'Koz  
2  Orianna      Aphelios    Maokai  
3     Ekko         Sivir      Pyke  
4     Yone       Orianna  Pantheon

### To collect all the unique champion names

In [6]:


col = ['BTop', 'BJng', 'BMid', 'BAdc', 'BSup', 'RTop', 'RJng',
       'RMid', 'RAdc', 'RSup']
champ= []
for i in col:
    tempchamp = df[i].unique()
    champ = np.append(champ,tempchamp)
    
    
#Converting the data to a series to extract unique values and converting it back to a list    
temp = pd.Series(champ)
champions = temp.unique()
champions = list(champions)

### Encoding champion name into numbers in order to make it easier for processing

In [7]:


#For one champion

for i in range(len(df)):
    for j in col:
        if(df.loc[i,j]=='Camille'):
            df.loc[i,j]=1
            

In [8]:
df.head()

winner    BTop     BJng    BMid    BAdc    BSup      RTop       RJng  \
0    Red       1   Gragas    Yone    Jhin   Brand      Shen     Graves   
1   Blue       1  Nidalee   Galio    Jhin  Anivia     Riven    Hecarim   
2   Blue  Irelia     Ekko   Annie  Kai'Sa  Thresh    Aatrox  Jarvan IV   
3    Red  Graves  Kindred   Sylas   Vayne    Bard  Renekton    Nidalee   
4    Red       1  Lee Sin  Lucian  Kai'Sa   Leona      Jhin    Nidalee   

      RMid          RAdc      RSup  
0    Sylas        Kai'Sa     Karma  
1   Xerath  Miss Fortune   Vel'Koz  
2  Orianna      Aphelios    Maokai  
3     Ekko         Sivir      Pyke  
4     Yone       Orianna  Pantheon

In [9]:
#For all champions

for k in range(len(champions)):
    for i in range(len(df)):
        for j in col:
            if(df.loc[i,j]==champions[k]):
                df.loc[i,j]=k
            

In [10]:
df.head()

winner BTop BJng BMid BAdc BSup RTop RJng RMid RAdc RSup
0    Red    1   33   27   76  110   12    3   11   88   43
1   Blue    1  129   54   76  100    7   17   64   66  105
2   Blue    2   32   18   88  139    8  113   75   78   52
3    Red    3  143   11   62  127    6  129   32  132   24
4    Red    1  123   26   88  135   76  129   27   75   37

In [11]:
#For all entries with Blue = 0 and Red = 1

for i in range(len(df)):
    if df.loc[i,'winner']=='Blue':
        df.loc[i,'Winner']=0
    else:
        df.loc[i,'Winner']=1
        
df['Winner'] = df['Winner'].astype(int)

In [12]:
df.head()

winner BTop BJng BMid BAdc BSup RTop RJng RMid RAdc RSup  Winner
0    Red    1   33   27   76  110   12    3   11   88   43       1
1   Blue    1  129   54   76  100    7   17   64   66  105       0
2   Blue    2   32   18   88  139    8  113   75   78   52       0
3    Red    3  143   11   62  127    6  129   32  132   24       1
4    Red    1  123   26   88  135   76  129   27   75   37       1

In [13]:
df.drop('winner',axis=1,inplace=True)

In [14]:
df.head()

BTop BJng BMid BAdc BSup RTop RJng RMid RAdc RSup  Winner
0    1   33   27   76  110   12    3   11   88   43       1
1    1  129   54   76  100    7   17   64   66  105       0
2    2   32   18   88  139    8  113   75   78   52       0
3    3  143   11   62  127    6  129   32  132   24       1
4    1  123   26   88  135   76  129   27   75   37       1

### Note that the above process of encoding champion names takes close to 7 mins. To prevent doing that action every single time, the converted data is exported

In [15]:
df.to_csv('../../data/interim/EncodedLOLData.csv',index=False) #Exporting the encoded data for further processing

### Lets perform Decision Trees and Random Forests

In [16]:
X = df.drop('Winner',axis=1)
y = df['Winner']

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
dtc = DecisionTreeClassifier()

In [21]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [22]:
predict_dtc = dtc.predict(X_test)

In [23]:
from sklearn.metrics import classification_report,confusion_matrix

In [24]:
print (confusion_matrix(y_test,predict_dtc))
print('\n')
print(classification_report(y_test,predict_dtc))

[[1534 1421]
 [1524 1425]]


              precision    recall  f1-score   support

           0       0.50      0.52      0.51      2955
           1       0.50      0.48      0.49      2949

    accuracy                           0.50      5904
   macro avg       0.50      0.50      0.50      5904
weighted avg       0.50      0.50      0.50      5904



### The results above show that for Decision Trees the precision isnt better than random chance. :(

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
rfc = RandomForestClassifier(n_estimators=300)

In [27]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [28]:
predict_rfc = rfc.predict(X_test)

In [29]:
print (confusion_matrix(y_test,predict_rfc))
print('\n')
print(classification_report(y_test,predict_rfc))

[[1595 1360]
 [1545 1404]]


              precision    recall  f1-score   support

           0       0.51      0.54      0.52      2955
           1       0.51      0.48      0.49      2949

    accuracy                           0.51      5904
   macro avg       0.51      0.51      0.51      5904
weighted avg       0.51      0.51      0.51      5904



### Unfortunately even Random Forests dont seem promising

### Possibly the next step we can do is encode every single champion name into a dummy variable and try it

In [30]:
X = pd.get_dummies(df[['BTop', 'BJng', 'BMid', 'BAdc', 'BSup', 'RTop', 'RJng', 'RMid', 'RAdc','RSup']])
y = df['Winner']

In [31]:
X.head()

BTop_1  BTop_2  BTop_3  BTop_4  BTop_5  BTop_6  BTop_7  BTop_8  BTop_9  \
0       1       0       0       0       0       0       0       0       0   
1       1       0       0       0       0       0       0       0       0   
2       0       1       0       0       0       0       0       0       0   
3       0       0       1       0       0       0       0       0       0   
4       1       0       0       0       0       0       0       0       0   

   BTop_10  ...  RSup_141  RSup_143  RSup_145  RSup_146  RSup_147  RSup_148  \
0        0  ...         0         0         0         0         0         0   
1        0  ...         0         0         0         0         0         0   
2        0  ...         0         0         0         0         0         0   
3        0  ...         0         0         0         0         0         0   
4        0  ...         0         0         0         0         0         0   

   RSup_149  RSup_150  RSup_152  RSup_153  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 1237 columns]

In [32]:
X.shape

(19679, 1237)

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [35]:
from sklearn.tree import DecisionTreeClassifier

In [36]:
dtc = DecisionTreeClassifier()

In [37]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [38]:
predict_dtc = dtc.predict(X_test)

In [39]:
from sklearn.metrics import classification_report,confusion_matrix

In [40]:
print (confusion_matrix(y_test,predict_dtc))
print('\n')
print(classification_report(y_test,predict_dtc))

[[1546 1409]
 [1480 1469]]


              precision    recall  f1-score   support

           0       0.51      0.52      0.52      2955
           1       0.51      0.50      0.50      2949

    accuracy                           0.51      5904
   macro avg       0.51      0.51      0.51      5904
weighted avg       0.51      0.51      0.51      5904



In [41]:
from sklearn.ensemble import RandomForestClassifier

In [42]:
rfc = RandomForestClassifier(n_estimators=300)

In [43]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [44]:
predict_rfc = rfc.predict(X_test)

In [45]:
print (confusion_matrix(y_test,predict_rfc))
print('\n')
print(classification_report(y_test,predict_rfc))

[[1694 1261]
 [1576 1373]]


              precision    recall  f1-score   support

           0       0.52      0.57      0.54      2955
           1       0.52      0.47      0.49      2949

    accuracy                           0.52      5904
   macro avg       0.52      0.52      0.52      5904
weighted avg       0.52      0.52      0.52      5904

