In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('../../data/interim/EncodedLOLData.csv')

In [3]:
df.head(5)

BTop  BJng  BMid  BAdc  BSup  RTop  RJng  RMid  RAdc  RSup  Winner
0     1    33    27    76   110    12     3    11    88    43       1
1     1   129    54    76   100     7    17    64    66   105       0
2     2    32    18    88   139     8   113    75    78    52       0
3     3   143    11    62   127     6   129    32   132    24       1
4     1   123    26    88   135    76   129    27    75    37       1

#### Lets try training the data without encoding every single champion using one hot enocder / dummies

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X = df.drop('Winner',axis=1)
y = df['Winner']

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [7]:
from sklearn.svm import SVC

In [8]:
svm = SVC()

In [9]:
svm.fit(X_train,y_train)

/Users/deepakbuddha/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [10]:
predictions = svm.predict(X_test)

In [11]:
from sklearn.metrics import classification_report,confusion_matrix

In [12]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[2955    0]
 [2949    0]]


              precision    recall  f1-score   support

           0       0.50      1.00      0.67      2955
           1       0.00      0.00      0.00      2949

    accuracy                           0.50      5904
   macro avg       0.25      0.50      0.33      5904
weighted avg       0.25      0.50      0.33      5904



/Users/deepakbuddha/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/deepakbuddha/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/deepakbuddha/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### Lets try using Gridsearch to get the optimum values for hyperparameters C and Gamma

In [13]:
from sklearn.model_selection import GridSearchCV

In [14]:
params = {'C':[0.1,1,10,100,1000],'gamma':[1,0.1,0.01,0.001,0.0001]}

In [15]:
grid = GridSearchCV(SVC(),params,verbose=3)

In [16]:
grid.fit(X_train,y_train)

/Users/deepakbuddha/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.506, total=   2.7s
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.7s remaining:    0.0s


[CV] ...................... C=0.1, gamma=1, score=0.506, total=   2.7s
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    5.4s remaining:    0.0s


[CV] ...................... C=0.1, gamma=1, score=0.506, total=   2.8s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.506, total=   3.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.506, total=   3.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.506, total=   3.1s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ................... C=0.1, gamma=0.01, score=0.506, total=   4.3s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ................... C=0.1, gamma=0.01, score=0.506, total=   4.2s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ................... C=0.1, gamma=0.01, score=0.506, total=   4.1s
[CV] C=0.1, gamma=0.001 ..............................................
[CV] .

[CV] ..................... C=1000, gamma=1, score=0.506, total=   5.4s
[CV] C=1000, gamma=1 .................................................
[CV] ..................... C=1000, gamma=1, score=0.506, total=   5.4s
[CV] C=1000, gamma=1 .................................................
[CV] ..................... C=1000, gamma=1, score=0.506, total=   5.3s
[CV] C=1000, gamma=0.1 ...............................................
[CV] ................... C=1000, gamma=0.1, score=0.506, total=   6.0s
[CV] C=1000, gamma=0.1 ...............................................
[CV] ................... C=1000, gamma=0.1, score=0.506, total=   5.9s
[CV] C=1000, gamma=0.1 ...............................................
[CV] ................... C=1000, gamma=0.1, score=0.506, total=   5.8s
[CV] C=1000, gamma=0.01 ..............................................
[CV] .................. C=1000, gamma=0.01, score=0.506, total=   8.1s
[CV] C=1000, gamma=0.01 ..............................................
[CV] .

[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed: 12.9min finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [17]:
grid_predictions = grid.predict(X_test)

In [18]:
print(confusion_matrix(y_test,grid_predictions))
print('\n')
print(classification_report(y_test,grid_predictions))

[[1488 1467]
 [1479 1470]]


              precision    recall  f1-score   support

           0       0.50      0.50      0.50      2955
           1       0.50      0.50      0.50      2949

    accuracy                           0.50      5904
   macro avg       0.50      0.50      0.50      5904
weighted avg       0.50      0.50      0.50      5904



### So we still end up getting a prediction score of 0.5

### Lets try again but now lets encode every single champion data

In [11]:
X = pd.get_dummies(data=df,columns=['BTop', 'BJng', 'BMid', 'BAdc', 'BSup', 'RTop', 'RJng', 'RMid', 'RAdc','RSup'])
y = df['Winner']

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=101)

In [13]:
from sklearn.svm import SVC

In [14]:
svm = SVC()

In [15]:
svm.fit(X_train,y_train)

/Users/deepakbuddha/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [16]:
predictions = svm.predict(X_test)

In [17]:
from sklearn.metrics import classification_report,confusion_matrix

In [18]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[2955    0]
 [   0 2949]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2955
           1       1.00      1.00      1.00      2949

    accuracy                           1.00      5904
   macro avg       1.00      1.00      1.00      5904
weighted avg       1.00      1.00      1.00      5904



### Lets try using Gridsearch to get the optimum values for hyperparameters C and Gamma

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
params = {'C':[0.1,1,10,100,1000],'gamma':[1,0.1,0.01,0.001,0.0001]}

In [21]:
grid = GridSearchCV(SVC(),params,verbose=3)

In [ ]:
grid.fit(X_train,y_train)

/Users/deepakbuddha/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.506, total= 5.5min
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  5.5min remaining:    0.0s


[CV] ...................... C=0.1, gamma=1, score=0.506, total= 5.4min
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 11.0min remaining:    0.0s


[CV] ...................... C=0.1, gamma=1, score=0.506, total= 5.5min
[CV] C=0.1, gamma=0.1 ................................................


In [ ]:
grid_predictions = grid.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,grid_predictions))
print('\n')
print(classification_report(y_test,grid_predictions))